# Generated by Django 4.2.17 on 2024-12-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailAttemptToSend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Успешно"),
                            ("failure", "Не успешно"),
                        ],
                        verbose_name="Статус",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        default="Успешно",
                        verbose_name="Ответ почтового сервера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": ("-attempt_date", "status"),
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        null=True, verbose_name="Время отправки"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        null=True, verbose_name="Время окончания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("finished", "Завершена"),
                        ],
                        default="created",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="Успешно"),
                ),
                (
                    "failure_count",
                    models.IntegerField(default=0, verbose_name="Не успешно"),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ("-start_date", "-end_date", "status"),
                "permissions": [
                    (
                        "can_manage_own_mailings",
                        "Может управлять собственными рассылками",
                    ),
                    (
                        "can_manage_all_mailings",
                        "Может управлять всеми рассылками",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=120, verbose_name="Тема"),
                ),
                ("body", models.TextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ("subject",),
                "permissions": [
                    ("can_edit_message", "Может редактировать сообщение"),
                    ("can_delete_message", "Может удалить сообщение"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Фамилия"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Отчество"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
                "ordering": ("first_name", "last_name"),
                "permissions": [
                    ("can_edit_recipient", "Можнет редактировать получателя"),
                    ("can_delete_recipient", "Может удалить получателя"),
                ],
            },
        ),
    ]
